version: '3.7'

networks:
    api:
      name: api_custom
      driver: bridge

services:
    auth:
      container_name: auth
      build:
        context: .
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - ${AUTH_PORT_API}:${AUTH_PORT_API}
        - 9229:9229
      command: yarn run start auth --watch
      env_file: .env
      #depends_on:
      #  - postgresqldb
      #links:
      #  - postgresqldb
      networks: 
        - api

    #postgresqldb:
    #  image: postgres:alpine
    #  env_file: .env
    #  ports:
    #    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    #  expose:
    #    - ${POSTGRES_PORT}
    #  hostname: postgres
    #  volumes:
    #  - ${POSTGRES_DATABASE_DOCKER_VOLUME}:/var/lib/postgresql/data
    #  environment:
    #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #    - POSTGRES_USER=${POSTGRES_USER}
    #    - POSTGRES_DB=${POSTGRES_DB}

